<main id="main">
    <div class="table">
        <table>
            <thead>
                <th>Prontuário</th>
                <th>Nome</th>
                <th>Ano</th>
                <th>Livros</th>
            </thead>
            <tbody>
                <tr>
                    <td>555566</td>
                    <td>Shiryu</td>
                    <td>1</td>
                    <td>
                        Química,
                        Artes,
                        Matemática
                    </td>
                </tr>
                <tr>
                    <td>9899985</td>
                    <td>Hyoga</td>
                    <td>2</td>
                    <td>
                        Química
                    </td>
                </tr>
                <tr>
                    <td>7777899</td>
                    <td>Ikki</td>
                    <td>4</td>
                    <td>
                            Matemática
                    </td>
                </tr>
                <tr>
                    <td>554448</td>
                    <td>Seiya</td>
                    <td>3</td>
                    <td>
                        Artes
                    </td>
                </tr>
                <tr>
                    <td>124441</td>
                    <td>Shun</td>
                    <td>3</td>
                    <td>
                        Química,
                        Matemática
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <a href="<?php echo INCLUDE_PATH_ROOT; ?>">
        <img src="<?php echo INCLUDE_PATH_VIEWS.'assets/icons/back.png'; ?>" alt="Voltar"/>
            Voltar
    </a>
</main>